feat: add overlapping elements
sinnerschrader/sinnerschrader-reboot pull request #10
Opened 2021-02-10 11:50 UTC by trinegl

2021-02-10 11:59 UTC, Wandkleister requested changes

2021-02-10 11:59 UTC, Wandkleister commented on styles/includes/_overlap.scss
> +	#overlap-bg-1 {
Please don't use IDs to style an element. The reason why I have linked for you below.
Use classes and you're good to go :)

https://softwareengineering.stackexchange.com/questions/271995/what-to-use-instead-of-ids-in-selectors-in-css#:~:text=IDs%20shouldn't%20be%20used,an%20element%20in%20the%20page.

2021-02-10 12:08 UTC, tam-kis commented on _includes/overlap.liquid
> +	<div class="overlap-img-wrapper col col-start-3 col-end-9 col-start-1-xs col-end-13-xs">
Let's use the BEM naming style so everyone writes the same (easier to understand afterwards, especially if someone is new to the project) : http://getbem.com/naming/

2021-02-10 12:13 UTC, tam-kis commented on styles/includes/_overlap.scss
> +	display: flex;
We shouldn't mix flexbox and css grid

2021-02-10 12:20 UTC, trinegl commented on styles/includes/_overlap.scss
> +	display: flex;
As I understand grid is generally used for layouts, flex for organising components in that layout - here I'm just using flex to center the text. Why shouldn't we mix the two?

2021-02-10 12:21 UTC, tam-kis commented on styles/core/_grid-test.scss
> +// .col {
I will remove the grid example in my next PR

2021-02-10 12:37 UTC, tam-kis commented on styles/includes/_overlap.scss
> +	display: flex;
It's best practice to stick to the grid system that was chosen, for example with css grid: https://coryrylan.com/blog/how-to-center-in-css-with-css-grid

2021-02-10 13:19 UTC, trinegl commented on styles/includes/_overlap.scss
> +	#overlap-bg-1 {
Thank you for the link :) Changed it!

2021-02-10 13:20 UTC, trinegl commented on _includes/overlap.liquid
> +	<div class="overlap-img-wrapper col col-start-3 col-end-9 col-start-1-xs col-end-13-xs">
Tried to implement it now, not sure if correct

2021-02-11 10:29 UTC, Wandkleister requested changes

2021-02-11 10:29 UTC, Wandkleister commented on _includes/overlap.liquid
> +	<div class="overlap-img col col-start-3 col-end-9 col-start-1-xs col-end-13-xs">
Playing the Party-Pooper here ^^ 

Let's get this BEM naming right. BEM = Block, Element, Modifier. So your block is "overlap" - you can think of this as the whole component. This div in line 2 is a container, or a wrapper - so we should name it like it: "overlap__container".
Its children are two image elements. So their name should be "overlap__image". And as you need to differ between the left and right image you will need to add a modifier to them. This gives you "overlap__image--left" and "overlap__image--right".

2021-02-11 10:29 UTC, Wandkleister commented on _includes/overlap.liquid
> +	<div class="overlap-img-wrapper col col-start-3 col-end-9 col-start-1-xs col-end-13-xs">
Resolving this, because we have a new discussion about that topic

2021-02-11 11:49 UTC, trinegl commented on _includes/overlap.liquid
> +	<div class="overlap-img col col-start-3 col-end-9 col-start-1-xs col-end-13-xs">
I think I got it now! It should be fixed now :) Thanks for the explanation (also, I didn't use right and left as modifier, since the images don't change behaviour or state at any point)

2021-02-11 13:26 UTC, Wandkleister approved these changes

2021-02-11 13:41 UTC, merged