fix(location):  name and id for locations
sinnerschrader/sinnerschrader-reboot pull request #121
Opened 2021-02-26 12:19 UTC by tam-kis

2021-02-26 12:47 UTC, timbru31 requested changes

2021-02-26 12:47 UTC, timbru31 commented on _includes/data/locations.json
> +				"name": "SinnerSchrader Deutschland",
I think we need to name it just `SinnerSchrader` everywhere and remove the `Deutschland`, too.

2021-02-26 12:49 UTC, tam-kis commented on _includes/data/locations.json
> +				"name": "SinnerSchrader Deutschland",
Ah, ok

2021-02-26 13:25 UTC, tam-kis commented on _includes/data/locations.json
> +				"name": "SinnerSchrader Deutschland",
Updated

2021-03-02 11:06 UTC, timbru31 approved these changes

2021-03-02 11:06 UTC, merged