feat: location section
sinnerschrader/sinnerschrader-reboot pull request #13
Opened 2021-02-10 16:15 UTC by luismeyer

2021-02-12 10:10 UTC, Wandkleister requested changes

2021-02-12 10:10 UTC, Wandkleister commented on _includes/js/locations.js
> +		console.log("... init Locations module ...");
Please get rid of this console.log :)

2021-02-12 10:10 UTC, Wandkleister commented on _includes/js/locations.js
> +			locationLink.classList.replace(this.LINK_UNSELECTED_CLASS, newClass);
Maybe its a good idea to just toggle one class?

2021-02-12 10:10 UTC, Wandkleister commented on _includes/js/utils.js
> +export const waitForInitialPaint = () => {
You basically reproduce an already built-in event: https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

And I'm generally confused that you need to wait for the initial paint. Why do you need it?

2021-02-12 10:21 UTC, tam-kis commented on styles/includes/locations.scss
> +	margin: 160px 0 96px;
Please use rem - it's divisable by 10,  so 160px is 16rem and 96px is 9.6rem

2021-02-12 10:33 UTC, luismeyer commented on _includes/js/utils.js
> +export const waitForInitialPaint = () => {
alright i'm gonna replace that. I needed it because JS threw an Error when it tried to register the click Handlers on elements that were not rendered yet

2021-02-12 10:37 UTC, luismeyer commented on _includes/default.liquid
>  </html>
i will leave this changes then and put "tabSize: 2" in our prettier file since all other files use this as well

2021-02-12 10:47 UTC, tam-kis commented on _includes/locations.liquid
> +            <div class="location-studio-content">
Here we can use the `<address>` html tag and add a list `<li>` of data

2021-02-12 10:59 UTC, luismeyer commented on _includes/js/locations.js
> +		console.log("... init Locations module ...");
done

2021-02-12 10:59 UTC, luismeyer commented on _includes/js/locations.js
> +			locationLink.classList.replace(this.LINK_UNSELECTED_CLASS, newClass);
done

2021-02-12 10:59 UTC, luismeyer commented on styles/includes/locations.scss
> +	margin: 160px 0 96px;
done in the scss variables

2021-02-12 11:00 UTC, luismeyer commented on _includes/locations.liquid
> +            <div class="location-studio-content">
done

2021-02-12 11:06 UTC, luismeyer commented on _includes/default.liquid
>  </html>
i just read the slack discussion and will revert the prettier change 😅

2021-02-12 12:29 UTC, tam-kis commented on _includes/locations.liquid
>                <h4>{{ studio.name }}</h4>
So for the `<address>` tag we put all the details inside: https://www.w3schools.com/tags/tag_address.asp

2021-02-12 13:04 UTC, timbru31 requested changes

2021-02-12 13:04 UTC, timbru31 commented on _data/locations.json
> +				"postal": "10245 Berlin",
```suggestion
				"street": "Bergmannstraße 72",
				"postal": "10961 Berlin",
```

2021-02-12 13:04 UTC, timbru31 commented on _includes/locations.liquid
> +
Do we really want two empty lines here? (Applies to other places, too)

2021-02-12 13:04 UTC, timbru31 commented on styles/core/_variables.scss
> +$spacing-200: todo;
Do we have those spacings already?

2021-02-12 13:10 UTC, luismeyer commented on styles/core/_variables.scss
> +$spacing-200: todo;
The spacings i found in figma were a bit confusing were the same spacing-key has different values in different screens. So i think we have to align all the variables again in a seperate commit

2021-02-12 13:11 UTC, luismeyer commented on _includes/locations.liquid
> +
fixed

2021-02-12 13:11 UTC, luismeyer commented on _includes/locations.liquid
>                <h4>{{ studio.name }}</h4>
fixed

2021-02-12 13:11 UTC, luismeyer commented on _data/locations.json
> +				"postal": "10245 Berlin",
fixed

2021-02-12 13:12 UTC, luismeyer commented
> Right now the selectable items on the left side are span-elements. This causes that we don't have keyboard accessibility and we would also need to add "cursor: pointer" to the styling of those elements, to make users understand that this is clickable.
> 
> A button or link element would solve this problem.
> 
> <img alt="Bildschirmfoto 2021-02-12 um 13 03 16" width="451" src="https://user-images.githubusercontent.com/10813871/107765820-bfe23f00-6d32-11eb-8c58-baf9da1e99a3.png">

i changed the labels to buttons

2021-02-15 09:04 UTC, timbru31 commented on styles/core/_variables.scss
> +$spacing-200: todo;
https://github.com/sinnerschrader/sinnerschrader-reboot/pull/18/files#diff-6b5230149ef89263aaa8e3ad218af6c46ed38781ad7ce07d697e39f7463311d7R24-R32 - seems Trine already figured them out. If you use the exact same code block, git will figure this without a merge conflict.

2021-02-15 11:50 UTC, tam-kis commented on _includes/locations.liquid
> +              <a href="mailto:{{ studio.email }}">{{ studio.email }}</a>
These two(email and phone number) should also be in the `<address>` tag.

2021-02-15 13:13 UTC, luismeyer commented on _includes/locations.liquid
> +              <a href="mailto:{{ studio.email }}">{{ studio.email }}</a>
done

2021-02-15 13:17 UTC, luismeyer commented on styles/core/_variables.scss
> +$spacing-200: todo;
done :)

2021-02-16 11:26 UTC, tam-kis approved these changes

2021-02-16 12:07 UTC, timbru31 commented on _includes/locations.liquid
> +                <br/><a href="tel:+49{{ studio.tel }}">{{ studio.tel }}</a>
This doesn't work with Prague or Zurich

2021-02-16 12:41 UTC, luismeyer commented on _includes/locations.liquid
> +                <br/><a href="tel:+49{{ studio.tel }}">{{ studio.tel }}</a>
fixed

2021-02-16 13:16 UTC, timbru31 approved these changes

2021-02-16 14:02 UTC, Wandkleister approved these changes

2021-02-16 14:28 UTC, merged