Feat/section header
sinnerschrader/sinnerschrader-reboot pull request #29
Opened 2021-02-16 16:26 UTC by luismeyer

2021-02-17 08:54 UTC, timbru31 requested changes
Can you please rebase the changes so the stylelint job runs? Otherwise, we might break the development branch.

2021-02-17 11:10 UTC, tam-kis commented on styles/includes/_section-header.scss
> +		margin-top: $spacing--200;
For all the margins we could just have: `margin: $spacing--200 0 $spacing--300--tablet 0; `
The positions for the margin are:
margin: top right bottom left;

2021-02-17 11:58 UTC, luismeyer commented on styles/includes/_section-header.scss
> +		margin-top: $spacing--200;
i think using the shorthand in this case wouldn't make that much sence. The lines will get kinda long and personally more unreadable. I think this is simpler and better to maintain. i would be interested in why you think the shorthand is better here? 🙂

2021-02-17 12:08 UTC, tam-kis commented on styles/includes/_section-header.scss
> +		margin-top: $spacing--200;
Just to avoid repeating the two everywhere when you can have just one, also having less lines of code. If it's less readable for you then we can keep it like this, for people who would join in the future aswell.

2021-02-17 12:09 UTC, tam-kis approved these changes

2021-02-18 09:56 UTC, timbru31 approved these changes

2021-02-18 09:56 UTC, timbru31 commented on _includes/head.liquid
> +  <script async language="javascript" src="bundle.js" type="text/javascript"></script>
The `language` attribute is deprecated and `type` should be used instead. Any special reason to include it here?

2021-02-18 09:56 UTC, timbru31 requested changes
.

2021-02-18 10:20 UTC, luismeyer commented on _includes/head.liquid
> +  <script async language="javascript" src="bundle.js" type="text/javascript"></script>
i just copied this from stackoverflow. Didn't know language is deprecated... i will remove it

2021-02-18 10:26 UTC, timbru31 approved these changes

2021-02-18 12:30 UTC, merged