Job teaser redesign and some other fixes
sinnerschrader/sinnerschrader-reboot pull request #398
Opened 2021-08-09 08:29 UTC by kernazhytskayalena

2021-11-17 14:39 UTC, moritzbehnke requested changes
Also please rebase to the latest development

2021-11-17 14:39 UTC, moritzbehnke commented on src/styles/includes/_job-teaser.scss
> +			height: 4.6rem;
Font is a tiny bit too low

2021-11-17 14:39 UTC, moritzbehnke commented on src/styles/includes/_job-teaser.scss
> +			height: 3.9rem;
Font is noticeably too low

2021-11-17 14:39 UTC, moritzbehnke commented on src/styles/includes/_job-teaser.scss
> +			height: 4.5rem;
Font is a tiny bit too low

2021-11-17 14:39 UTC, moritzbehnke commented on src/_data/landingpage.json
> +			"logoPart1": {
How about namig the keys and images a little bit more clearer? For this one maybe `logoLeftHalf`.

2021-11-17 14:39 UTC, moritzbehnke commented on src/_data/landingpage.json
> +			"logoPart2": {
For this one maybe `logoRightHalf`

2021-11-17 14:39 UTC, moritzbehnke commented on src/_data/landingpage.json
> +				"src": "/assets/svg/element1.svg",
For this one maybe `ovalShape`

2021-11-17 14:39 UTC, moritzbehnke commented on src/_data/landingpage.json
> +			"element2": {
For this one maybe `circleShape`

2022-03-23 15:31 UTC, wheelmaker24 commented
I've tried to rebase this branch onto the current development branch, but failed. Any idea on how to proceed with this branch? @moritzbehnke ? ;)

2022-03-24 11:14 UTC, evgenypastushek commented
@wheelmaker24 
here is new PR https://github.com/sinnerschrader/sinnerschrader-reboot/pull/747
this one can be closed

2022-03-29 19:15 UTC, closed without merging