feat(animation): animation setup
sinnerschrader/sinnerschrader-reboot pull request #40
Opened 2021-02-19 11:49 UTC by tam-kis

2021-02-19 12:28 UTC, Wandkleister requested changes

2021-02-19 12:28 UTC, Wandkleister commented on _includes/js/main.js
> +window.onload = () => {
Please don't use an Event Listener here. This caused loading problems and was fixed this morning on the development branch. If you need to listen to the load event of the window object, you'll need to do that in your component.
```suggestion
(() => {
```

2021-02-19 12:28 UTC, Wandkleister commented on _includes/js/main.js
> +};
```suggestion
})();
```

2021-02-19 12:34 UTC, luismeyer commented on styles/includes/_footer.scss
> +	top: -5.9rem;
this creates a gap between the footer and the accenture thingy. i this wanted?

2021-02-23 09:41 UTC, tam-kis commented on styles/includes/_footer.scss
> +	top: -5.9rem;
This change now fixes the overlapping

2021-02-23 09:47 UTC, Wandkleister approved these changes

2021-02-23 09:57 UTC, merged