Improvement: Update header logo to svg
sinnerschrader/sinnerschrader-reboot pull request #453
Opened 2021-09-13 08:03 UTC by evgenypastushek

Improvement from vsevolod.vlasenko@sinnerschrader.com

2021-09-17 15:46 UTC, s2-pauher requested changes

2021-09-17 15:46 UTC, s2-pauher commented on src/_includes/sinnerschrader-header-logo.liquid
> +    <title id="sinnerSchrader">Sinner Schrader</title>
I would change the title to `SinnerSchrader Part of Accenture Interactive` to reflect the content of the svg.

2021-09-17 15:46 UTC, s2-pauher commented on src/_includes/navigation.liquid
> -			<p class="nav__logo--accenture">
Please also delete the class `nav__logo--accenture` from the `_navigation.scss` as it's not needed anymore.

2021-09-17 15:46 UTC, s2-pauher commented on src/_includes/navigation.liquid
>  			<a class="nav__logo--sinnerschrader" href="/" >
Since you just have one child left, you could select it directly using the `a` selector. This way you don't need this css class anymore.

Also the overall alignment of the logo is not in place with the menu items. Before the "SinnerSchrader" was at the same height as the menu items. Please refer to the design in figma.

2021-09-20 08:11 UTC, evgenypastushek commented on src/_includes/sinnerschrader-header-logo.liquid
> +    <title id="sinnerSchrader">Sinner Schrader</title>
done

2021-09-20 08:11 UTC, evgenypastushek commented on src/_includes/navigation.liquid
> -			<p class="nav__logo--accenture">
done

2021-09-20 08:20 UTC, evgenypastushek commented on src/_includes/navigation.liquid
>  			<a class="nav__logo--sinnerschrader" href="/" >
done

2021-09-27 15:50 UTC, s2-pauher requested changes

2021-09-27 15:50 UTC, s2-pauher commented on src/styles/includes/_navigation.scss
>  		&--sinnerschrader {
This class is not needed anymore

2021-09-27 15:50 UTC, s2-pauher commented on src/_includes/sinnerschrader-header-logo.liquid
> +    <title id="sinnerSchrader">SinnerSchrader Part of Accenture Interactive</title>
As the id of an html element is the unique identifier it should be as descriptive as possible. I would suggest to choose something like `id="sinnerSchraderLogoTitle"`.

2021-09-27 15:51 UTC, s2-pauher commented on src/_includes/navigation.liquid
>  			<a class="nav__logo--sinnerschrader" href="/" >
According to the figma design, the „SinnerSchrader“ part of the logo should have the same font height as the other menu items. 
Please have another look at that.

2021-09-29 07:33 UTC, evgenypastushek commented on src/_includes/sinnerschrader-header-logo.liquid
> +    <title id="sinnerSchrader">SinnerSchrader Part of Accenture Interactive</title>
done

2021-09-29 07:33 UTC, evgenypastushek commented on src/styles/includes/_navigation.scss
>  		&--sinnerschrader {
done

2021-11-17 13:11 UTC, merged