feat: Career page leave your profile
sinnerschrader/sinnerschrader-reboot pull request #485
Opened 2021-10-08 12:43 UTC by grohj

2021-11-09 10:33 UTC, moritzbehnke requested changes

2021-11-09 10:33 UTC, moritzbehnke commented on src/styles/includes/_profile-link-contact-form.scss
> +	&__sendProfileButton {
@s2-pauher Do we need this style? Can't we use the button from the form components?

2021-11-30 08:10 UTC, s2-pauher commented on src/styles/includes/_profile-link-contact-form.scss
> +	&__sendProfileButton {
As discussed we'll keep this style for now.

2021-11-30 11:34 UTC, moritzbehnke approved these changes

2021-11-30 11:34 UTC, merged