fix(safari): switch fallback file format to jpg, adjust fallback type…
sinnerschrader/sinnerschrader-reboot pull request #71
Opened 2021-02-23 18:01 UTC by Wandkleister

… of video

2021-02-23 19:15 UTC, tam-kis approved these changes

2021-02-24 08:01 UTC, luismeyer requested changes
you have to adjust the locations.js file aswell. For lazy loading the sources are updated there everytime the location changes.

2021-02-24 10:07 UTC, Wandkleister commented
> you have to adjust the locations.js file aswell. For lazy loading the sources are updated there everytime the location changes.
Thanks for the hint - its fixed now

2021-02-24 10:32 UTC, luismeyer approved these changes

2021-02-24 10:33 UTC, merged